package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/coagente/multiverso/internal/agent"
	"github.com/coagente/multiverso/internal/object"
	"github.com/coagente/multiverso/internal/oracle"
	"github.com/coagente/multiverso/internal/race"
	"github.com/coagente/multiverso/internal/workspace"
)

// agentOnlyFlags may only be used with an agent adapter (claude-code or
// codex); with --agent script they are usage errors.
var agentOnlyFlags = []string{
	"prompt", "prompt-file", "model", "candidates",
	"max-usd", "max-turns", "max-wall-ms", "agent-env",
}

// cmdRace wires the workspace into the race orchestrator (CP-2, CP-3):
// one T0 worktree world per candidate, generated by the selected agent
// adapter (AG-1), one suite oracle run per COMPLETED world, then the pure
// decision function. All engine logic lives in internal/race.
func cmdRace(args []string, stdout, stderr io.Writer) error {
	digArg, rest := splitDigestArg(args)
	fs := newFlagSet("race", stderr)
	dir := fs.String("dir", ".", "repository directory")
	agentName := fs.String("agent", "script", "adapter: script, claude-code, or codex")
	patchesDir := fs.String("patches", "", "directory with candidate patch files (script adapter)")
	oracleCmd := fs.String("oracle-cmd", "", "suite oracle command (required)")
	keepWorlds := fs.Bool("keep-worlds", false, "keep world worktrees after the race")
	prompt := fs.String("prompt", "", "task override text (agent adapters; default: intent spec)")
	promptFile := fs.String("prompt-file", "", "task override file (agent adapters)")
	model := fs.String("model", "", "model pool NAME[,NAME...], round-robin across worlds (AG-5)")
	candidates := fs.Int("candidates", 0, "candidate count (agent adapters; default: intent budget max_candidates)")
	maxUSD := fs.String("max-usd", "", "per-world USD budget, decimal with at most 6 fractional digits")
	maxTurns := fs.Int("max-turns", 0, "per-world native turn cap (0 = uncapped)")
	maxWallMS := fs.Int64("max-wall-ms", 0, "per-world watchdog in ms (default: intent budget max_wall_ms)")
	agentEnv := fs.String("agent-env", "", "extra env var NAME[,NAME...] passed through to the agent")
	if err := parseFlags(fs, rest); err != nil {
		return err
	}
	digArg, err := positionalDigest(digArg, fs, "race")
	if err != nil {
		return err
	}
	argv := strings.Fields(*oracleCmd)
	if len(argv) == 0 {
		return usagef("race: --oracle-cmd is required")
	}

	set := map[string]bool{}
	fs.Visit(func(f *flag.Flag) { set[f.Name] = true })

	isScript := *agentName == "script"
	if isScript {
		for _, name := range agentOnlyFlags {
			if set[name] {
				return usagef("race: --%s requires an agent adapter (--agent claude-code|codex)", name)
			}
		}
		if *patchesDir == "" {
			return usagef("race: --patches is required with --agent script")
		}
	} else {
		if set["patches"] {
			return usagef("race: --patches applies only to --agent script")
		}
		if set["prompt"] && set["prompt-file"] {
			return usagef("race: --prompt and --prompt-file are mutually exclusive")
		}
	}
	ad, err := agent.New(*agentName)
	if err != nil {
		return usagef("race: %v", err)
	}
	var budgetUSDMicro int64
	if *maxUSD != "" {
		if budgetUSDMicro, err = agent.ParseUSDMicro(*maxUSD); err != nil {
			return usagef("race: --max-usd: %v", err)
		}
	}

	ws, err := workspace.Open(*dir)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}
	defer ws.Close()

	st, err := loadState(ws.Ledger)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}
	intentDig, intent, err := st.resolveIntent(digArg)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}

	var cands []race.Candidate
	if isScript {
		if cands, err = scriptCandidates(*patchesDir); err != nil {
			return fmt.Errorf("race: %w", err)
		}
	} else {
		if cands, err = agentCandidates(agentFlagValues{
			prompt: *prompt, promptFile: *promptFile, model: *model,
			candidates: *candidates, candidatesSet: set["candidates"],
			maxWallMS: *maxWallMS, maxWallSet: set["max-wall-ms"],
			maxTurns: *maxTurns, usdMicro: budgetUSDMicro, env: *agentEnv,
		}, intent); err != nil {
			return err
		}
		// Pre-flight the adapter binary so a missing CLI aborts here
		// instead of burning N CONFIG_ERROR worlds (decision 10).
		if bin := agent.Binary(ad); bin != "" {
			if _, err := exec.LookPath(bin); err != nil {
				return fmt.Errorf("race: adapter %s: binary %q not found in PATH: %w", *agentName, bin, err)
			}
		}
	}

	res, err := race.Run(context.Background(), race.Config{
		Repo:       ws.Root,
		Ledger:     ws.Ledger,
		CAS:        ws.CAS,
		Intent:     intentDig,
		Adapter:    ad,
		Candidates: cands,
		WorldsDir:  ws.WorldsDir(),
		Oracle: &oracle.CommandOracle{
			Argv:    argv,
			Timeout: time.Duration(intent.Budget.MaxWallMS) * time.Millisecond,
			CAS:     ws.CAS,
		},
		KeepWorlds: *keepWorlds,
	})
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}

	dec := res.Decision
	if dec.Type == race.TypeSelect && len(dec.Subject) > 0 {
		fmt.Fprintf(stdout, "SELECT %s (decision %s, %d worlds)\n",
			dec.Subject[0], res.DecisionDigest, len(res.Worlds))
	} else {
		fmt.Fprintf(stdout, "%s (decision %s, %d worlds)\n",
			dec.Type, res.DecisionDigest, len(res.Worlds))
	}
	return nil
}

// scriptCandidates builds one candidate per patch file in dir, sorted by
// filename — the deterministic world order (CP-2). The patch bytes ARE the
// prompt (design decision 7).
func scriptCandidates(dir string) ([]race.Candidate, error) {
	entries, err := os.ReadDir(dir) // sorted by filename
	if err != nil {
		return nil, fmt.Errorf("list patches: %w", err)
	}
	var cands []race.Candidate
	for _, e := range entries {
		if e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("read patch %s: %w", e.Name(), err)
		}
		cands = append(cands, race.Candidate{Prompt: string(b)})
	}
	if len(cands) == 0 {
		return nil, fmt.Errorf("no patch files in %s", dir)
	}
	return cands, nil
}

// agentFlagValues carries the parsed agent flags into candidate building.
type agentFlagValues struct {
	prompt        string
	promptFile    string
	model         string
	candidates    int
	candidatesSet bool
	maxWallMS     int64
	maxWallSet    bool
	maxTurns      int
	usdMicro      int64
	env           string
}

// agentCandidates renders N per-world prompts (AG-5: ordinal variation +
// model pool round-robin) under one shared budget.
func agentCandidates(fv agentFlagValues, intent object.Intent) ([]race.Candidate, error) {
	n := intent.Budget.MaxCandidates
	if fv.candidatesSet {
		n = fv.candidates
	}
	if n < 1 {
		return nil, usagef("race: --candidates must be at least 1")
	}
	if n > intent.Budget.MaxCandidates {
		return nil, usagef("race: --candidates %d exceeds intent budget max_candidates=%d (CP-2)",
			n, intent.Budget.MaxCandidates)
	}
	task := fv.prompt
	if fv.promptFile != "" {
		b, err := os.ReadFile(fv.promptFile)
		if err != nil {
			return nil, fmt.Errorf("race: read --prompt-file: %w", err)
		}
		task = string(b)
	}
	wallMS := intent.Budget.MaxWallMS
	if fv.maxWallSet {
		wallMS = fv.maxWallMS
	}
	if wallMS <= 0 {
		// An uncapped paid agent run is never launched implicitly; pass the
		// intent's own bound explicitly if that is intended by design.
		return nil, usagef("race: --max-wall-ms must be positive for agent adapters")
	}
	if fv.maxTurns < 0 {
		return nil, usagef("race: --max-turns must not be negative")
	}
	budget := agent.Budget{
		MaxWall:     time.Duration(wallMS) * time.Millisecond,
		MaxTurns:    fv.maxTurns,
		MaxUSDMicro: fv.usdMicro,
	}
	pool := splitList(fv.model)
	env := splitList(fv.env)
	cands := make([]race.Candidate, 0, n)
	for k := 1; k <= n; k++ {
		m := ""
		if len(pool) > 0 {
			m = pool[(k-1)%len(pool)] // round-robin model pool (AG-5)
		}
		cands = append(cands, race.Candidate{
			Prompt: agent.RenderPrompt(intent.Spec, k, n, task),
			Model:  m,
			Budget: budget,
			Env:    env,
		})
	}
	return cands, nil
}

// splitList splits a comma-separated flag value, trimming spaces and
// dropping empty items; nil for an empty value.
func splitList(s string) []string {
	if s == "" {
		return nil
	}
	var out []string
	for _, part := range strings.Split(s, ",") {
		if part = strings.TrimSpace(part); part != "" {
			out = append(out, part)
		}
	}
	return out
}
