package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/coagente/multiverso/internal/agent"
	"github.com/coagente/multiverso/internal/backend"
	"github.com/coagente/multiverso/internal/dockerx"
	"github.com/coagente/multiverso/internal/object"
	"github.com/coagente/multiverso/internal/oracle"
	"github.com/coagente/multiverso/internal/policy"
	"github.com/coagente/multiverso/internal/race"
	"github.com/coagente/multiverso/internal/workspace"
)

// agentOnlyFlags may only be used with an agent adapter (claude-code or
// codex); with --agent script they are usage errors. --parallel and
// --exec compose freely with every adapter (M1c).
var agentOnlyFlags = []string{
	"prompt", "prompt-file", "model", "candidates",
	"max-usd", "max-turns", "max-wall-ms", "agent-env",
}

// t1OnlyFlags may only be used with --exec T1.
var t1OnlyFlags = []string{"exec-image", "memory-mb", "cpus", "pids", "allow-network"}

// cmdRace wires the workspace into the race orchestrator (CP-2, CP-3):
// one T0 worktree world per candidate, generated by the selected agent
// adapter (AG-1), one suite oracle run per COMPLETED world, then the pure
// decision function. All engine logic lives in internal/race.
func cmdRace(args []string, stdout, stderr io.Writer) error {
	digArg, rest := splitDigestArg(args)
	fs := newFlagSet("race", stderr)
	dir := fs.String("dir", ".", "repository directory")
	agentName := fs.String("agent", "script", "adapter: script, claude-code, or codex")
	patchesDir := fs.String("patches", "", "directory with candidate patch files (script adapter)")
	oracleCmd := fs.String("oracle-cmd", "", "suite oracle command (required)")
	keepWorlds := fs.Bool("keep-worlds", false, "keep world worktrees after the race")
	prompt := fs.String("prompt", "", "task override text (agent adapters; default: intent spec)")
	promptFile := fs.String("prompt-file", "", "task override file (agent adapters)")
	model := fs.String("model", "", "model pool NAME[,NAME...], round-robin across worlds (AG-5)")
	candidates := fs.Int("candidates", 0, "candidate count (agent adapters; default: intent budget max_candidates)")
	maxUSD := fs.String("max-usd", "", "per-world USD budget, decimal with at most 6 fractional digits")
	maxTurns := fs.Int("max-turns", 0, "per-world native turn cap (0 = uncapped)")
	maxWallMS := fs.Int64("max-wall-ms", 0, "per-world watchdog in ms (default: intent budget max_wall_ms)")
	agentEnv := fs.String("agent-env", "", "extra env var NAME[,NAME...] passed through to the agent")
	parallel := fs.Int("parallel", 1, "bounded worker count; 1 = the sequential schedule")
	execTier := fs.String("exec", "T0", "execution backend tier: T0 (worktree) or T1 (container)")
	execImage := fs.String("exec-image", "", "container image reference (required with --exec T1)")
	memoryMB := fs.Int64("memory-mb", 0, "per-world memory cap in MiB (T1; 0 = uncapped, docker floor 6)")
	cpus := fs.String("cpus", "", "per-world CPU cap, decimal with at most 3 fractional digits (T1)")
	pids := fs.Int64("pids", 0, "per-world pids-limit (T1; 0 = uncapped)")
	allowNetwork := fs.Bool("allow-network", false, "T1 joins the default bridge instead of --network none (NFR-4 opt-out)")
	if err := parseFlags(fs, rest); err != nil {
		return err
	}
	digArg, err := positionalDigest(digArg, fs, "race")
	if err != nil {
		return err
	}
	oracleArgv := strings.Fields(*oracleCmd)

	set := map[string]bool{}
	fs.Visit(func(f *flag.Flag) { set[f.Name] = true })

	// The adapter name is validated BEFORE the flag-combination rules.
	// Checked the other way round, `--agent gpt5 --patches DIR` reported
	// "--patches applies only to --agent script" — blaming a flag the user
	// spelled correctly for a typo in one they did not.
	ad, err := agent.New(*agentName)
	if err != nil {
		return usagef("race: %v", err)
	}

	isScript := *agentName == "script"
	if isScript {
		for _, name := range agentOnlyFlags {
			if set[name] {
				return usagef("race: --%s requires an agent adapter (--agent claude-code|codex)", name)
			}
		}
		if *patchesDir == "" {
			return usagef("race: --patches is required with --agent script")
		}
	} else {
		if set["patches"] {
			return usagef("race: --patches applies only to --agent script")
		}
		if set["prompt"] && set["prompt-file"] {
			return usagef("race: --prompt and --prompt-file are mutually exclusive")
		}
	}
	var budgetUSDMicro int64
	if *maxUSD != "" {
		if budgetUSDMicro, err = agent.ParseUSDMicro(*maxUSD); err != nil {
			return usagef("race: --max-usd: %v", err)
		}
	}

	// M1c flag discipline: --parallel and --exec compose freely with every
	// adapter; the T1 knobs require --exec T1.
	if *parallel < 1 {
		return usagef("race: --parallel must be at least 1")
	}
	isT1 := false
	switch *execTier {
	case "T0":
	case "T1":
		isT1 = true
	default:
		return usagef("race: --exec must be T0 or T1 (got %q)", *execTier)
	}
	if !isT1 {
		for _, name := range t1OnlyFlags {
			if set[name] {
				return usagef("race: --%s requires --exec T1", name)
			}
		}
	} else if *execImage == "" {
		return usagef("race: --exec T1 requires --exec-image")
	}
	if set["memory-mb"] && *memoryMB < 6 {
		return usagef("race: --memory-mb must be at least 6 (docker's own floor)")
	}
	if set["pids"] && *pids < 1 {
		return usagef("race: --pids must be at least 1")
	}
	var cpuMilli int64
	if *cpus != "" {
		if cpuMilli, err = dockerx.ParseCPUMilli(*cpus); err != nil {
			return usagef("race: --cpus: %v", err)
		}
	}

	ws, err := workspace.Open(*dir)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}
	defer ws.Close()

	st, err := loadState(ws.Ledger)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}
	intentDig, intent, err := st.resolveIntent(digArg)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}

	// The intent's PINNED policy decides whether --oracle-cmd is required,
	// forbidden, or (never) optional — M1e decision 18. A v0 policy names a
	// gate but not the command that decides it, so two machines could
	// satisfy the same attested policy with different suites; that hole is
	// closed by refusing the flag wherever the policy can name its own
	// oracles, and by keeping it mandatory where it cannot.
	pol, err := policy.Load(ws.CAS, intent.Policy)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}
	isLegacy := pol.Dialect == policy.DialectV0
	switch {
	case isLegacy && len(oracleArgv) == 0:
		return usagef("race: --oracle-cmd is required with policy %s (%s): the policy names a gate but not the command that decides it (M1e decision 18)",
			pol.Digest, policy.SchemaShort(pol.Schema))
	case !isLegacy && set["oracle-cmd"]:
		return usagef("race: --oracle-cmd is not permitted with policy %s (%s): the policy names its own oracles",
			pol.Digest, policy.SchemaShort(pol.Schema))
	}

	var cands []race.Candidate
	if isScript {
		if cands, err = scriptCandidates(*patchesDir); err != nil {
			return fmt.Errorf("race: %w", err)
		}
	} else {
		if cands, err = agentCandidates(agentFlagValues{
			prompt: *prompt, promptFile: *promptFile, model: *model,
			candidates: *candidates, candidatesSet: set["candidates"],
			maxWallMS: *maxWallMS, maxWallSet: set["max-wall-ms"],
			maxTurns: *maxTurns, usdMicro: budgetUSDMicro, env: *agentEnv,
		}, intent); err != nil {
			return err
		}
		// T0 pre-flight: the adapter binary must exist on the host so a
		// missing CLI aborts here instead of burning N CONFIG_ERROR worlds
		// (M1b decision 10). Under T1 the in-image probe below replaces
		// this — the CLI must live in the image, not on the host.
		if bin := agent.Binary(ad); bin != "" && !isT1 {
			if _, err := exec.LookPath(bin); err != nil {
				return fmt.Errorf("race: adapter %s: binary %q not found in PATH: %w", *agentName, bin, err)
			}
		}
	}

	// T1 pre-flight (M1c decision 18): before race.Run, hence before
	// race.started — a failure here is a machinery error with exit 1 and
	// the ledger stays empty of race events.
	bcfg := backend.Config{}
	if isT1 {
		if err := dockerx.Available(); err != nil {
			return fmt.Errorf("race: exec T1: docker daemon unavailable (is Docker running?): %v", err)
		}
		img, err := dockerx.ResolveImage(*execImage)
		if err != nil {
			return fmt.Errorf("race: exec T1: %v", err)
		}
		if img.OS != "linux" {
			return fmt.Errorf("race: exec T1: image %s runs %q, want linux", *execImage, img.OS)
		}
		if bin := agent.Binary(ad); bin != "" {
			if err := probeImageBinary(img, bin); err != nil {
				return fmt.Errorf("race: exec T1: adapter %s: %v", *agentName, err)
			}
		}
		bcfg = backend.Config{
			Tier:         object.TierT1Container,
			Image:        img,
			CPUMilli:     cpuMilli,
			MemoryMB:     *memoryMB,
			PidsLimit:    *pids,
			AllowNetwork: *allowNetwork,
			KeeperTTL:    keeperTTL(intent),
			IntentDigest: intentDig,
		}
	}
	be, err := backend.New(bcfg)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}

	// Under v0 the supplied command IS the gate; its receipt keeps M0's
	// config digest (empty Config), so ledgers written before M1e replay
	// byte-for-byte. Under v1 the orchestrator builds the policy's own
	// instances and this stays nil.
	var legacy oracle.Oracle
	if isLegacy {
		legacy = &oracle.CommandOracle{
			Argv:    oracleArgv,
			Timeout: time.Duration(intent.Budget.MaxWallMS) * time.Millisecond,
			CAS:     ws.CAS,
		}
	}

	res, err := race.Run(context.Background(), race.Config{
		Repo:         ws.Root,
		Ledger:       ws.Ledger,
		CAS:          ws.CAS,
		Intent:       intentDig,
		Adapter:      ad,
		Candidates:   cands,
		WorldsDir:    ws.WorldsDir(),
		Backend:      be,
		Parallel:     *parallel,
		KeepWorlds:   *keepWorlds,
		LegacyOracle: legacy,
	})
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}

	dec := res.Decision
	if dec.Type == race.TypeSelect && len(dec.Subject) > 0 {
		fmt.Fprintf(stdout, "SELECT %s (decision %s, %d worlds)\n",
			dec.Subject[0], res.DecisionDigest, len(res.Worlds))
	} else {
		fmt.Fprintf(stdout, "%s (decision %s, %d worlds)\n",
			dec.Type, res.DecisionDigest, len(res.Worlds))
	}
	return nil
}

// scriptCandidates builds one candidate per patch file in dir, sorted by
// filename — the deterministic world order (CP-2). The patch bytes ARE the
// prompt (design decision 7).
func scriptCandidates(dir string) ([]race.Candidate, error) {
	entries, err := os.ReadDir(dir) // sorted by filename
	if err != nil {
		return nil, fmt.Errorf("list patches: %w", err)
	}
	var cands []race.Candidate
	for _, e := range entries {
		if e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("read patch %s: %w", e.Name(), err)
		}
		cands = append(cands, race.Candidate{Prompt: string(b)})
	}
	if len(cands) == 0 {
		return nil, fmt.Errorf("no patch files in %s", dir)
	}
	return cands, nil
}

// agentFlagValues carries the parsed agent flags into candidate building.
type agentFlagValues struct {
	prompt        string
	promptFile    string
	model         string
	candidates    int
	candidatesSet bool
	maxWallMS     int64
	maxWallSet    bool
	maxTurns      int
	usdMicro      int64
	env           string
}

// agentCandidates renders N per-world prompts (AG-5: ordinal variation +
// model pool round-robin) under one shared budget.
func agentCandidates(fv agentFlagValues, intent object.Intent) ([]race.Candidate, error) {
	n := intent.Budget.MaxCandidates
	if fv.candidatesSet {
		n = fv.candidates
	}
	if n < 1 {
		return nil, usagef("race: --candidates must be at least 1")
	}
	if n > intent.Budget.MaxCandidates {
		return nil, usagef("race: --candidates %d exceeds intent budget max_candidates=%d (CP-2) — an intent's budget is pinned at creation, so raise it on a NEW intent with `mvo intent new --budget-candidates %d`",
			n, intent.Budget.MaxCandidates, n)
	}
	task := fv.prompt
	if fv.promptFile != "" {
		b, err := os.ReadFile(fv.promptFile)
		if err != nil {
			return nil, fmt.Errorf("race: read --prompt-file: %w", err)
		}
		task = string(b)
	}
	wallMS := intent.Budget.MaxWallMS
	if fv.maxWallSet {
		wallMS = fv.maxWallMS
	}
	if wallMS <= 0 {
		// An uncapped paid agent run is never launched implicitly; pass the
		// intent's own bound explicitly if that is intended by design.
		return nil, usagef("race: --max-wall-ms must be positive for agent adapters")
	}
	if fv.maxTurns < 0 {
		return nil, usagef("race: --max-turns must not be negative")
	}
	budget := agent.Budget{
		MaxWall:     time.Duration(wallMS) * time.Millisecond,
		MaxTurns:    fv.maxTurns,
		MaxUSDMicro: fv.usdMicro,
	}
	pool := splitList(fv.model)
	env := splitList(fv.env)
	cands := make([]race.Candidate, 0, n)
	for k := 1; k <= n; k++ {
		m := ""
		if len(pool) > 0 {
			m = pool[(k-1)%len(pool)] // round-robin model pool (AG-5)
		}
		cands = append(cands, race.Candidate{
			Prompt: agent.RenderPrompt(intent.Spec, k, n, task),
			Model:  m,
			Budget: budget,
			Env:    env,
		})
	}
	return cands, nil
}

// probeTimeout bounds the pre-flight in-image binary probe: a CLI whose
// --version never exits, or a wedged daemon, must not hang mvo at
// pre-flight (M1c decision 18).
const probeTimeout = 60 * time.Second

// probeImageBinary is the T1 replacement for the host LookPath pre-flight
// (M1c decision 18): the adapter CLI must exist IN THE IMAGE, proven by a
// one-shot `docker run --rm --network none --entrypoint <bin> <pinned-ref>
// --version` — same rationale as M1b: never burn N CONFIG_ERROR worlds
// discovering a missing CLI. Bounded by probeTimeout; unlike the keeper,
// the probe container has no TTL backstop (its --rm fires only on exit),
// so on expiry the named container is force-removed.
func probeImageBinary(img dockerx.Image, bin string) error {
	ctx, cancel := context.WithTimeout(context.Background(), probeTimeout)
	defer cancel()
	suffix := make([]byte, 6)
	if _, err := rand.Read(suffix); err != nil {
		return fmt.Errorf("probe name entropy: %w", err)
	}
	name := "mvo-probe-" + hex.EncodeToString(suffix)
	cmd := exec.CommandContext(ctx, "docker", "run", "--rm", "--name", name,
		"--network", "none", "--entrypoint", bin, img.RunRef, "--version")
	cmd.Env = dockerx.ClientEnv()
	out, err := cmd.CombinedOutput()
	if ctx.Err() != nil {
		_ = dockerx.Remove(name) // the killed client cannot fire --rm for a still-running probe
		return fmt.Errorf("binary %q probe in image %s timed out after %s", bin, img.Ref, probeTimeout)
	}
	if err != nil {
		return fmt.Errorf("binary %q not runnable in image %s: %v: %s",
			bin, img.Ref, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// keeperTTL derives the container self-expiry from the intent budget (M1c
// decision 4): max_wall_ms in seconds rounded up plus 600 s slack, 86400 s
// when the intent has no wall budget — a crashed mvo leaves no immortal
// container.
func keeperTTL(intent object.Intent) time.Duration {
	if intent.Budget.MaxWallMS <= 0 {
		return 86400 * time.Second
	}
	secs := (intent.Budget.MaxWallMS + 999) / 1000
	return time.Duration(secs+600) * time.Second
}

// splitList splits a comma-separated flag value, trimming spaces and
// dropping empty items; nil for an empty value.
func splitList(s string) []string {
	if s == "" {
		return nil
	}
	var out []string
	for _, part := range strings.Split(s, ",") {
		if part = strings.TrimSpace(part); part != "" {
			out = append(out, part)
		}
	}
	return out
}
