package race

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"github.com/coagente/multiverso/internal/agent"
	"github.com/coagente/multiverso/internal/cas"
	"github.com/coagente/multiverso/internal/gitx"
	"github.com/coagente/multiverso/internal/ledger"
	"github.com/coagente/multiverso/internal/object"
	"github.com/coagente/multiverso/internal/oracle"
)

const isolationTier = "T0-worktree"

// lockfileNames are hashed into the env manifest when present in a world.
var lockfileNames = []string{
	"Cargo.lock", "go.sum", "package-lock.json",
	"poetry.lock", "requirements.txt", "uv.lock",
}

// Candidate is one world's generation spec (AG-5): the literal prompt, a
// pinned model, and the per-world budget the adapter enforces (AG-2).
type Candidate struct {
	Prompt string       // literal prompt text (script: patch bytes as a string)
	Model  string       // model pin; "" = tool default
	Budget agent.Budget // per-world budget (AG-2)
	Env    []string     // extra parent env var NAMES passed through (names only, decision 14)
}

// Config wires one race run. All fields are required except KeepWorlds.
type Config struct {
	Repo       string         // git repo root; worlds are worktrees of it
	Ledger     *ledger.Ledger // event log
	CAS        *cas.Store     // object + artifact store
	Intent     string         // intent digest ("mv0:...") already in CAS
	Adapter    agent.Adapter  // generator for every world (AG-1)
	Candidates []Candidate    // one world per candidate, len ≥ 1 (CP-2)
	WorldsDir  string         // parent directory for world worktrees
	Oracle     oracle.Oracle  // verifier run in each COMPLETED world
	KeepWorlds bool           // keep worktrees after the race (--keep-worlds)
}

// WorldRun is one world's trajectory through the race.
type WorldRun struct {
	Ordinal       int // 1-based candidate ordinal
	Dir           string
	Digest        string
	World         object.World
	Run           *agent.RunResult
	ReceiptDigest string          // "" for worlds that produced no receipt
	Receipt       *object.Receipt // nil for worlds that produced no receipt
}

// Result is what a race produced.
type Result struct {
	Decision       object.Decision
	DecisionDigest string
	Worlds         []WorldRun
}

// Run executes the v0 race (CP-2, CP-3): sequential worlds, one per
// candidate, generated by the configured adapter; the control plane
// captures each world's diff (AG-4) and transcript (AG-3); one oracle run
// per COMPLETED world; then one recorded decision. Every object is stored
// in CAS and appended to the ledger as it is created. Agent failure is
// evidence and the race continues; a non-nil error means evidence itself
// could not be produced and the race aborts (decision 10).
func Run(ctx context.Context, cfg Config) (*Result, error) {
	if err := cfg.validate(); err != nil {
		return nil, err
	}

	var intent object.Intent
	if err := loadObject(cfg.CAS, cfg.Intent, &intent); err != nil {
		return nil, err
	}
	if intent.Schema != object.SchemaIntent {
		return nil, fmt.Errorf("race: %s has schema %q, want %q", cfg.Intent, intent.Schema, object.SchemaIntent)
	}
	policy, err := LoadPolicy(cfg.CAS, intent.Policy)
	if err != nil {
		return nil, err
	}
	// CP-2: the candidate count is hard-capped before race.started — an
	// over-budget race is refused, never recorded (closes the M0 TODO).
	if len(cfg.Candidates) > intent.Budget.MaxCandidates {
		return nil, fmt.Errorf("race: %d candidates exceed intent budget max_candidates=%d (CP-2)",
			len(cfg.Candidates), intent.Budget.MaxCandidates)
	}
	// Budget: MaxWallMS bounds the whole race; per-world wall budgets are
	// the candidates' own (agent watchdog, AG-2).
	if intent.Budget.MaxWallMS > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, time.Duration(intent.Budget.MaxWallMS)*time.Millisecond)
		defer cancel()
	}

	adapterID := cfg.Adapter.ID() + "@" + cfg.Adapter.Version()

	// Each race gets its own fresh directory under WorldsDir (unique via
	// MkdirTemp): re-racing an intent is a first-class flow, so world paths
	// must never collide with worktrees left behind by --keep-worlds or a
	// crashed race. Created before race.started so a broken worlds dir
	// cannot leave a dangling half-race in the permanent ledger.
	if err := os.MkdirAll(cfg.WorldsDir, 0o755); err != nil {
		return nil, fmt.Errorf("race: create worlds dir: %w", err)
	}
	raceDir, err := os.MkdirTemp(cfg.WorldsDir, "race-")
	if err != nil {
		return nil, fmt.Errorf("race: create race worlds dir: %w", err)
	}

	if err := appendEvent(cfg.Ledger, "race.started", map[string]any{
		"adapter": adapterID, "candidates": len(cfg.Candidates), "intent": cfg.Intent,
	}); err != nil {
		os.Remove(raceDir)
		return nil, err
	}

	// Worlds are removed however Run exits, unless the caller keeps them.
	var worktrees []string
	removed := false
	defer func() {
		if cfg.KeepWorlds || removed {
			return
		}
		for _, dir := range worktrees {
			_ = removeWorld(cfg.Repo, dir) // best effort on error paths
		}
		_ = os.Remove(raceDir) // fails harmlessly if a world survived
	}()

	runs := make([]WorldRun, 0, len(cfg.Candidates))
	for i, cand := range cfg.Candidates {
		ordinal := i + 1
		dir := filepath.Join(raceDir, fmt.Sprintf("%03d", ordinal))
		if err := gitx.AddWorktree(cfg.Repo, dir, intent.Base.Commit); err != nil {
			return nil, fmt.Errorf("race: world %d: %w", ordinal, err)
		}
		worktrees = append(worktrees, dir)

		// World.Context = CAS key of the literal prompt bytes for every
		// adapter (DP-3; for script the prompt IS the patch, decision 7).
		contextKey, err := cfg.CAS.Put([]byte(cand.Prompt))
		if err != nil {
			return nil, fmt.Errorf("race: store context %d: %w", ordinal, err)
		}
		envNames := cand.Env // allowlisted NAMES only, never values (decision 14)
		if envNames == nil {
			envNames = []string{}
		}
		if err := appendEvent(cfg.Ledger, "agent.started", map[string]any{
			"adapter": adapterID,
			"budget": map[string]any{
				"max_turns":     cand.Budget.MaxTurns,
				"max_usd_micro": cand.Budget.MaxUSDMicro,
				"max_wall_ms":   cand.Budget.MaxWall.Milliseconds(),
			},
			"context": contextKey,
			"env":     envNames,
			"intent":  cfg.Intent,
			"model":   cand.Model,
			"ordinal": ordinal,
		}); err != nil {
			return nil, err
		}

		h, err := cfg.Adapter.Start(ctx, agent.RunSpec{
			WorldDir: dir,
			Prompt:   cand.Prompt,
			Model:    cand.Model,
			Budget:   cand.Budget,
			Env:      cand.Env,
		})
		if err != nil {
			return nil, fmt.Errorf("race: world %d: %w", ordinal, err)
		}
		res, err := h.Wait()
		if err != nil {
			return nil, fmt.Errorf("race: world %d: %w", ordinal, err)
		}

		// Post-run evidence capture. The worktree is the agent's write
		// surface, so a capture failure here is agent-induced damage —
		// evidence, not machinery failure (decision 10): the world is
		// recorded as CRASH, the error text is preserved in the stderr
		// artifact, and the race continues. Only control-plane failures
		// (CAS, ledger) abort the race.
		outcome := res.Outcome
		captureNote := ""
		captureFail := func(stage string, err error) {
			outcome = object.OutcomeCrash
			captureNote += "mvo: capture " + stage + ": " + err.Error() + "\n"
		}

		// AG-4: the control plane captures the diff; adapter output is
		// never consulted. An empty patch is legal (agent did nothing).
		// The worktree's `.git` pointer is a plain agent-writable file,
		// so first verify the world's git identity is still the control
		// plane's — a repointed worktree would make the "captured" patch
		// and tree agent-chosen.
		var patch []byte
		// Fallback when no post-run tree is capturable: record the base
		// tree the agent was handed (the CRASH outcome, not the tree,
		// carries the verdict; CRASH worlds get no oracle run and no
		// receipt binds to this tree).
		tree := intent.Base.Tree
		if err := gitx.VerifyWorktreeRepo(cfg.Repo, dir); err != nil {
			captureFail("git identity", err)
		} else {
			p, err := agent.Diff(dir, intent.Base.Tree)
			if err != nil {
				captureFail("diff", err)
			} else {
				patch = p
			}
			// Always the ACTUAL post-run tree: for a failed script apply,
			// git apply --index is atomic, so this equals the base tree.
			t, err := gitx.WriteTree(dir)
			if err != nil {
				captureFail("write-tree", err)
			} else {
				tree = t
			}
		}
		patchKey, err := cfg.CAS.Put(patch)
		if err != nil {
			return nil, fmt.Errorf("race: store patch %d: %w", ordinal, err)
		}
		traceKey, err := cfg.CAS.Put(res.Transcript)
		if err != nil {
			return nil, fmt.Errorf("race: store transcript %d: %w", ordinal, err)
		}
		stderrBytes := res.Stderr
		if captureNote != "" {
			stderrBytes = append(bytes.Clone(res.Stderr), captureNote...)
		}
		stderrKey, err := cfg.CAS.Put(stderrBytes)
		if err != nil {
			return nil, fmt.Errorf("race: store stderr %d: %w", ordinal, err)
		}
		// agent.finished records the RUN's own terminal state; a capture
		// failure downgrades only the World's outcome (the run may have
		// completed while the worktree it left behind is unusable as
		// evidence — both facts are recorded honestly).
		if err := appendEvent(cfg.Ledger, "agent.finished", map[string]any{
			"context":    contextKey,
			"exit_code":  res.ExitCode,
			"intent":     cfg.Intent,
			"killed_by":  res.KilledBy,
			"num_turns":  res.NumTurns,
			"ordinal":    ordinal,
			"outcome":    res.Outcome,
			"session":    res.SessionID,
			"stderr":     stderrKey,
			"tokens_in":  res.Cost.TokensIn,
			"tokens_out": res.Cost.TokensOut,
			"transcript": traceKey,
			"usd_micro":  res.Cost.USDMicro,
			"wall_ms":    res.Cost.WallMS,
		}); err != nil {
			return nil, err
		}

		env, err := EnvDigest(cfg.CAS, dir)
		if err != nil {
			return nil, err
		}
		w := object.World{
			Schema:        object.SchemaWorld,
			Intent:        cfg.Intent,
			Tree:          tree,
			Env:           env,
			IsolationTier: isolationTier,
			Producer: object.Producer{
				Adapter:      adapterID,
				Model:        cand.Model, // the PINNED model (what we asked for)
				IdentityTier: "claimed",
				Role:         "generator",
			},
			Context:   contextKey,
			Patch:     patchKey,
			Trace:     traceKey,
			Cost:      res.Cost,
			Outcome:   outcome,
			CreatedAt: nowRFC3339(),
		}
		dig, err := recordObject(cfg, "world.created", w)
		if err != nil {
			return nil, err
		}
		runs = append(runs, WorldRun{Ordinal: ordinal, Dir: dir, Digest: dig, World: w, Run: res})
	}

	worlds := make([]object.World, 0, len(runs))
	receipts := make([]object.Receipt, 0, len(runs))
	for i := range runs {
		worlds = append(worlds, runs[i].World)
		// The oracle runs only in COMPLETED worlds (unchanged M0 rule):
		// non-COMPLETED worlds get no suite receipt, therefore fail
		// suite-pass generically.
		if runs[i].World.Outcome != object.OutcomeCompleted {
			continue
		}
		rec, err := cfg.Oracle.Run(ctx, runs[i].Dir)
		if err != nil {
			return nil, fmt.Errorf("race: oracle in %s: %w", runs[i].Dir, err)
		}
		// The orchestrator alone knows the world digest and tree the
		// receipt attests to (valid_for.tree = the world's tree digest).
		rec.World = runs[i].Digest
		rec.Freshness.ValidFor = object.ValidFor{Tree: runs[i].World.Tree, Env: runs[i].World.Env}
		dig, err := recordObject(cfg, "receipt.recorded", rec)
		if err != nil {
			return nil, err
		}
		runs[i].Receipt = &rec
		runs[i].ReceiptDigest = dig
		receipts = append(receipts, rec)
	}

	decision := Decide(policy, worlds, receipts)
	decision.CreatedAt = nowRFC3339()
	decisionDig, err := recordObject(cfg, "decision.recorded", decision)
	if err != nil {
		return nil, err
	}
	if err := appendEvent(cfg.Ledger, "race.finished", map[string]any{
		"intent": cfg.Intent, "decision": decisionDig,
	}); err != nil {
		return nil, err
	}

	if !cfg.KeepWorlds {
		removed = true
		for _, dir := range worktrees {
			if err := removeWorld(cfg.Repo, dir); err != nil {
				return nil, err
			}
		}
		if err := os.Remove(raceDir); err != nil {
			return nil, fmt.Errorf("race: cleanup: %w", err)
		}
	}
	return &Result{Decision: decision, DecisionDigest: decisionDig, Worlds: runs}, nil
}

// removeWorld removes one world worktree, falling back to plain directory
// removal plus a registration prune when `git worktree remove` refuses —
// a hostile agent can corrupt a worktree's git metadata, and by cleanup
// time every piece of evidence is already recorded, so a damaged world
// must not fail the race.
func removeWorld(repo, dir string) error {
	if err := gitx.RemoveWorktree(repo, dir); err == nil {
		return nil
	}
	if err := os.RemoveAll(dir); err != nil {
		return fmt.Errorf("race: cleanup %s: %w", dir, err)
	}
	if err := gitx.PruneWorktrees(repo); err != nil {
		return fmt.Errorf("race: cleanup: %w", err)
	}
	return nil
}

func (cfg Config) validate() error {
	switch {
	case cfg.Repo == "":
		return errors.New("race: config: empty repo")
	case cfg.Ledger == nil:
		return errors.New("race: config: nil ledger")
	case cfg.CAS == nil:
		return errors.New("race: config: nil CAS")
	case cfg.Intent == "":
		return errors.New("race: config: empty intent digest")
	case cfg.Adapter == nil:
		return errors.New("race: config: nil adapter")
	case len(cfg.Candidates) == 0:
		return errors.New("race: config: no candidates")
	case cfg.WorldsDir == "":
		return errors.New("race: config: empty worlds dir")
	case cfg.Oracle == nil:
		return errors.New("race: config: nil oracle")
	}
	return nil
}

// recordObject digests v, stores its canonical bytes in CAS, and appends
// them to the ledger under typ. Returns the object digest.
func recordObject(cfg Config, typ string, v any) (string, error) {
	dig, canon, err := object.Digest(v)
	if err != nil {
		return "", fmt.Errorf("race: digest %s: %w", typ, err)
	}
	if _, err := cfg.CAS.Put(canon); err != nil {
		return "", fmt.Errorf("race: store %s: %w", typ, err)
	}
	if _, err := cfg.Ledger.Append(typ, canon); err != nil {
		return "", fmt.Errorf("race: record %s: %w", typ, err)
	}
	return dig, nil
}

func appendEvent(led *ledger.Ledger, typ string, body map[string]any) error {
	payload, err := object.Canonical(body)
	if err != nil {
		return fmt.Errorf("race: encode %s: %w", typ, err)
	}
	if _, err := led.Append(typ, payload); err != nil {
		return fmt.Errorf("race: record %s: %w", typ, err)
	}
	return nil
}

// LoadPolicy fetches a Policy object from CAS by its digest and validates
// its schema. Race runs and audit replay share it: both must read the same
// policy the same way (NFR-1).
func LoadPolicy(store *cas.Store, dig string) (object.Policy, error) {
	var pol object.Policy
	if err := loadObject(store, dig, &pol); err != nil {
		return pol, err
	}
	if pol.Schema != object.SchemaPolicy {
		return pol, fmt.Errorf("race: policy %s has schema %q, want %q", dig, pol.Schema, object.SchemaPolicy)
	}
	return pol, nil
}

// loadObject fetches an object's canonical bytes from CAS by its "mv0:"
// digest and decodes them into v.
func loadObject(store *cas.Store, dig string, v any) error {
	key, err := object.CASKey(dig)
	if err != nil {
		return fmt.Errorf("race: %w", err)
	}
	b, err := store.Get(key)
	if err != nil {
		return fmt.Errorf("race: load %s: %w", dig, err)
	}
	if err := json.Unmarshal(b, v); err != nil {
		return fmt.Errorf("race: decode %s: %w", dig, err)
	}
	return nil
}

// maxLockfileBytes caps how much of a lockfile EnvDigest reads. The dir
// may be a just-raced world whose files are agent-written: hashing must
// never turn into an unbounded read.
const maxLockfileBytes = 64 << 20

// EnvDigest builds the M0 env manifest for a directory —
// {"go":"none","os":runtime.GOOS} plus sha256 hashes of any recognized
// lockfiles — stores its canonical bytes in CAS, and returns its digest.
// Exported for admit, which records the same manifest for landing trees.
// Only plain, readable files under maxLockfileBytes are hashed: a hostile
// agent's FIFO at a lockfile name would block ReadFile forever (the agent
// is dead, no writer ever arrives) and a symlink to a device would read
// unboundedly. Skipped entries are simply absent from the manifest — the
// world's tree digest still records the file itself. A returned error is
// therefore always a control-plane (digest/CAS) failure.
func EnvDigest(store *cas.Store, dir string) (string, error) {
	manifest := map[string]any{"go": "none", "os": runtime.GOOS}
	locks := map[string]any{}
	for _, name := range lockfileNames {
		path := filepath.Join(dir, name)
		fi, err := os.Lstat(path)
		if err != nil {
			continue // absent (or unstatable: nothing honest to hash)
		}
		if !fi.Mode().IsRegular() || fi.Size() > maxLockfileBytes {
			continue // FIFOs, symlinks, devices, oversized: never opened
		}
		b, err := os.ReadFile(path)
		if err != nil {
			continue // unreadable (e.g. chmod 000): nothing honest to hash
		}
		sum := sha256.Sum256(b)
		locks[name] = "sha256:" + hex.EncodeToString(sum[:])
	}
	if len(locks) > 0 {
		manifest["lockfiles"] = locks
	}
	dig, canon, err := object.Digest(manifest)
	if err != nil {
		return "", fmt.Errorf("race: digest env manifest: %w", err)
	}
	if _, err := store.Put(canon); err != nil {
		return "", fmt.Errorf("race: store env manifest: %w", err)
	}
	return dig, nil
}

func nowRFC3339() string {
	return time.Now().UTC().Format(time.RFC3339)
}
